export const exhibitions = [
  {
    id: 1,
    title: "Gerhard Richter: Abstrakte Bilder",
    museum: "Hamburger Kunsthalle",
    city: "Hamburg",
    date: "10. März – 15. Juni 2026",
    image: "https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?w=600&q=80",
    tag: "Abstrakt",
    genre: "Abstrakt",
    color: "#c8a882",
    ticketUrl: "https://www.hamburger-kunsthalle.de/tickets",
    description: "Eine umfassende Retrospektive der abstrakten Werke des bedeutenden deutschen Künstlers."
  },
  {
    id: 2,
    title: "Caspar David Friedrich",
    museum: "Alte Nationalgalerie",
    city: "Berlin",
    date: "1. Feb – 30. Apr 2026",
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&q=80",
    tag: "Romantik",
    genre: "Romantik",
    color: "#8899aa",
    ticketUrl: "https://www.smb.museum/tickets",
    description: "Eine umfassende Retrospektive der abstrakten Werke des bedeutenden deutschen Künstlers."
  },
  {
    id: 3,
    title: "Bauhaus & Moderne",
    museum: "Museum Ludwig",
    city: "Köln",
    date: "20. März – 20. Juli 2026",
    image: "https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=600&q=80",
    tag: "Design",
    genre: "Design",
    color: "#b5a0c8",
    ticketUrl: "https://shop.museum-ludwig.de/webshop/webticket/timeslot",
    description: "Eine umfassende Retrospektive der abstrakten Werke des bedeutenden deutschen Künstlers."
  },
  {
    id: 4,
    title: "Expressionismus heute",
    museum: "Städel Museum",
    city: "Frankfurt",
    date: "5. Apr – 10. Aug 2026",
    image: "https://images.unsplash.com/photo-1547891654-e66ed7ebb968?w=600&q=80",
    tag: "Expressionismus",
    genre: "Expressionismus",
    color: "#c88888",
    ticketUrl: "https://www.staedelmuseum.de/tickets",
    description: "Eine umfassende Retrospektive der abstrakten Werke des bedeutenden deutschen Künstlers."
  },
  {
    id: 5,
    title: "Neue Sachlichkeit",
    museum: "Kunsthalle München",
    city: "München",
    date: "1. März – 1. Juni 2026",
    image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&q=80",
    tag: "Realismus",
    genre: "Realismus",
    color: "#a8b890",
    ticketUrl: "https://kunsthalle-muc.ticketfritz.de",
    description: "Eine umfassende Retrospektive der abstrakten Werke des bedeutenden deutschen Künstlers."
  },
  {
    id: 6,
    title: "Fotografie der Moderne",
    museum: "C/O Berlin",
    city: "Berlin",
    date: "15. März – 15. Juli 2026",
    image: "https://images.unsplash.com/photo-1554048612-b6a482bc67e5?w=600&q=80",
    tag: "Fotografie",
    genre: "Fotografie",
    color: "#8899aa",
    ticketUrl: "https://co-berlin.org/de/besuch/tickets#",
    description: "Eine umfassende Retrospektive der abstrakten Werke des bedeutenden deutschen Künstlers."
  },
];